on:
  workflow_call:
  
    inputs:
      artifact:
        required: true
        type: string

      repository:
        required: true
        type: string
      
      tags:
        required: true
        type: string

      artifactname:
        required: true
        type: string
  
jobs:
 build-docker-image:
   runs-on: ubuntu-latest
   steps:
      -
        name: Checkout
        uses: actions/checkout@v3

      # - name: run script 
      #   run: | 
      #      echo  ${{ secrets.docker_username}}
       
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ vars.DOCKERHUB_TOKEN }}

      - uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifactname }}
          
      - name: Display structure of downloaded files
        run: ls -R

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/resnet50-model:latest