on:
  workflow_call:
    # inputs:
    #   projectPath:
    #     required: true
    #     type: string
    #     default: '**.csproj'

jobs:

 python-build-code:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3
     
     - uses: actions/setup-python@v4
       with:
          python-version: '3.10' 
     
     - run: python export-resnet50.py