name: dotnet package

on: [push]

jobs:

  build-project:
    uses: mitzen/pytorch_restnet_flask_app/.github/workflows/build.yaml@master
    with:
      projectPath: dotnet-gaction.csproj

  build-image:
    uses: mitzen/pytorch_restnet_flask_app/.github/workflows/buildimage.yaml@master
    needs: build-project

    with:
      artifact: build-artifact
      repository: kepung
      tags: "resnet50-onnx"
      artifactname: resnet50-onnx
    # secrets:
    #   docker_username: ${{ secrets.DOCKERUSER}} 
    #   docker_token: ${{ secrets.DOCKERUSER}}
